### ISSUE TITLE
终端调试测试提示：格式化参数失败，公共参数中找不到first_currency。

### ISSUE THREAD

**Issue by wengyangjie** [ChenSen5/api_autotest#4]
<pre>
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.734 sec <<< FAILURE!
apiTest(test.com.sen.api.ApiTest)  Time elapsed: 0.415 sec  <<< FAILURE!
java.lang.NullPointerException
        at test.com.sen.api.TestBase.getBuildValue(TestBase.java:169)
        at test.com.sen.api.TestBase.verifyResult(TestBase.java:149)
        at test.com.sen.api.ApiTest.apiTest(ApiTest.java:188)

apiTest(test.com.sen.api.ApiTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: 格式化参数失败，公共参数中找不到first_currency。 expected object to not be null
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.assertNotNull(Assert.java:404)
        at test.com.sen.api.TestBase.getCommonParam(TestBase.java:112)
        at test.com.sen.api.ApiTest.parseUrl(ApiTest.java:259)
        at test.com.sen.api.ApiTest.parseHttpRequest(ApiTest.java:218)
        at test.com.sen.api.ApiTest.apiTest(ApiTest.java:140)

~
</pre>

**Comment by ChenSen5** [comment]
因为第一个接口执行验证失败导致获取不到数据，所以第二条用例就格式化失败了。

**Comment by wengyangjie** [comment]
🤦‍♂️尴尬

**Comment by ChenSen5** [comment]
我这个只是模板，你换换成你真实可用的。

**Comment by wengyangjie** [comment]
> 我这个只是模板，你换换成你真实可用的。

好的谢谢 正在摸索中
